version: "3.8"

services:
  backend:
    image: prabal864/chat-app:backend-01  # Your backend image name
    container_name: backend-container
    ports:
      - "5000:5000"        # Expose backend API on port 5000
    networks:
      - app-network

  frontend:
    image: prabal864/chat-app:frontend-01
    container_name: frontend-container
    ports:
      - "5173:5173"        # Expose frontend on port 3000
    depends_on:
      - backend 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
